---
title: '2022-04-12'
author: "Cynthia Petrossian"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../Outputs/")
```

# Load Libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(patchwork)
```

# Read In Data
```{r}
indoor_pollution <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-12/indoor_pollution.csv')
view(indoor_pollution)
```

# Data Wrangling
```{r}
usa <- indoor_pollution %>% 
  filter(Entity == "United States") %>% #filter only us data
  rename("Deaths" = "Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: Age-standardized (Percent)") #rename deaths... column
view(usa)

uk <- indoor_pollution %>% 
  filter(Entity == "United Kingdom") %>% #filter only uk data
  rename("Deaths" = "Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: Age-standardized (Percent)") #rename deaths... column
view(uk)
```

# Making USA Plot
```{r USA}
usaplot <- ggplot(data = usa, aes(x = Year, #ggplot - set x as year
                       y = Deaths))+ #set y as deaths
  geom_area(fill = "firebrick")+ #geom to area, fill as firebrick red
  labs(title = "Rate of Deaths Caused By Indoor Pollution in the United States", #add title
       subtitle = "1990-2019", #add subtitle
       caption = "Source: OurWorldInData.org") #add source caption
usaplot
```
# Making UK Plot
```{r UK}
ukplot <- ggplot(data = uk, aes(x = Year, #ggplot - set x as year
                       y = Deaths))+ #set y as deaths
  geom_area(fill = "firebrick")+ #geom to area, fill as firebrick red
  labs(title = "Rate of Deaths Caused By Indoor Pollution in the United Kingdom", #add title
       subtitle = "1990-2019", #add subtitle
       caption = "Source: OurWorldInData.org") #add source caption
ukplot
```

# Using Patchwork to Join Plots
```{r USA+UK}
usaplot/ukplot #use patchwork to put plots on top of each other
```

